### PR TITLE
escape escape characters when parsing json

### PR DESCRIPTION
**Pull request by slnovak**
### What ###

I noticed that escape characters (such as `\n`) are not escaped in the Netsuite reply. This PR escapes `\t`, `\n`, and `\r` prior to parsing the JSON reply.

Just a quick background.

Works:
```ruby
>> reply = "[\"foo\"]"
>> JSON.parse(reply)
=> ["foo"]
```

Doesn't work:
```ruby
>> reply = "[\"foo\nbar\"]"
>> JSON.parse(reply)
JSON::ParserError: 399: unexpected token at '"foo
bar"]'
```

However, this works:
```ruby
>> reply = "[\"foo\nbar\"]"
>> escaped_reply = reply.gsub(/(\t|\r|\n)/){ Regexp.escape($1) }
>> JSON.parse(escaped_reply)
=> ["foo\nbar"]
>> puts _[0]
foo
bar
```

### CODE REVIEW

**Comment by jmdeldin** [comment]
Nice fix! Mind adding a spec?

**Comment by jmdeldin** [comment]
Disregard... we don't have a sandbox environment and I can't find demo creds for NS, so tests are unusable.

:cake:

**Comment by hexgnu** [comment]
It seems like you can only test in production with netsuite anyways :(

**Comment by jmdeldin** [comment]
Nothing suiter than YOLO driven development.

**Pull request merged**
